optparse: _check_builtin is overzealous
With the last modification, options that should not be typed are broken.
For example:

    $ ./spip-admin action -q
    Fatal error: Uncaught exception 'OptionError' with message 'Unknown
    type: %(type)s' in
    /home/gfilion/workspace/projets_externes/spip-admin/optparse.php:924
    [stack trace cut ...]

This was caused by _check_builtin being too strict about what it
converts or not.

Remove the "default:" clause to let untranslated types to pass through.
At the same time, remove the useless "string" case.